# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d084ec465bd35fd43f1e83ad5acea888d2291893c451de2416be7adce7aeffa3cd28342eb95623ea87daaf697773b11dce161b297c06bc788eddde0afef71a5a

test:
  secret_key_base: 15abfa27af48878c649ca034c0b17e8c9822e6f7cb1f180e8b33cf36049493610f78d1cb5f93347222fd7231176f78b1bde7aa8f402e74596261ad81cb7ed1d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 15abfa27af48878c649ca034c0b17e8c9822e6f7cb1f180e8b33cf36049493610f78d1cb5f93347222fd7231176f78b1bde7aa8f402e74596261ad81cb7ed1d9

