source 'https://rubygems.org'

gem 'therubyracer', '~>0.12.1'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.4'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development
gem 'rabl', '~> 0.10.1'
gem 'twilio-ruby', '~> 3.11.6'
gem 'pg'
gem 'phone'
gem 'jquery-rails'
gem 'turbolinks'
gem 'apns'